In [1]:
import pandas as pd

# Reading Data

In [2]:
df = pd.read_csv(r'F:\Programming\Python\Project\Covid 19 Solution\data.csv')

In [3]:
df.head()

        fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0   98.610963         0   54          1           0              1
1  101.211489         1   49          0           0              1
2   99.808486         0   52          1          -1              0
3   98.870883         1   15          1           1              0
4  101.963638         0   71          1           1              1

In [4]:
df.tail()

           fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1995   98.210756         0   70          0          -1              1
1996  101.649188         1   41          0           1              1
1997  101.541826         1   54          0           0              1
1998  100.771969         0   58          1           1              1
1999  101.184913         1   39          1          -1              0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
fever            2000 non-null float64
bodyPain         2000 non-null int64
age              2000 non-null int64
runnyNose        2000 non-null int64
diffBreath       2000 non-null int64
infectionProb    2000 non-null int64
dtypes: float64(1), int64(5)
memory usage: 93.8 KB

In [6]:
df['diffBreath'].value_counts()

 1    702
-1    655
 0    643
Name: diffBreath, dtype: int64

In [7]:
df.describe()

,fever,bodyPain,age,runnyNose,diffBreath,infectionProb
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,99.965701,0.497000,50.648000,0.503500,0.023500,0.505500
std,1.177356,0.500116,28.245849,0.500113,0.823582,0.500095
min,98.000145,0.000000,1.000000,0.000000,-1.000000,0.000000
25%,98.906384,0.000000,27.000000,0.000000,-1.000000,0.000000
50%,99.991551,0.000000,51.000000,1.000000,0.000000,1.000000
75%,100.975710,1.000000,75.000000,1.000000,1.000000,1.000000
max,101.999606,1.000000,100.000000,1.000000,1.000000,1.000000

# Train Test Splitting

In [8]:
import numpy as np

In [9]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [10]:
train, test = data_split(df, 0.2)

In [11]:
train

           fever  bodyPain  age  runnyNose  diffBreath  infectionProb
968    98.003345         1   22          0           0              0
240   101.468463         0   76          0           1              0
819    98.244355         0   47          1           0              1
692    99.411353         1   56          1           1              1
420   101.783319         1    6          0           1              0
1085  101.824581         1   73          0           0              0
1998  100.771969         0   58          1           1              1
365    98.244421         1   56          1           1              0
1022  101.618934         1   79          1           0              0
1240  100.398494         1   17          1           1              1
588   100.373550         1   58          1           0              1
736    98.804355         1   95          1          -1              0
1761  100.445944         1   51          1           0              0
941    98.624097         1   44          1           0              0
71    100.522438         1   49          0           1              0
1407   98.432227         1   50          1           0              1
259   101.718278         0    2          1          -1              1
51    101.072057         1   78          0          -1              1
198   101.558949         0   12          1           0              0
1788   98.390607         1   58          1          -1              0
650    99.083069         0   50          1          -1              1
332   100.225135         0   23          0           1              0
1359   98.434532         1    2          1          -1              1
593   100.444794         0   43          1           1              0
1391   99.754574         0   68          1           0              1
1800  101.660309         1   29          1           0              1
1314  101.324261         1   18          1           1              1
1111   98.421287         0   65          0           1              0
1006   98.586301         1   19          1           1              1
1326  100.768344         1   72          1          -1              0
...          ...       ...  ...        ...         ...            ...
955   100.901206         0   65          1          -1              1
1215   98.114116         0   30          1           1              1
385   100.272580         0   72          0           1              0
805    99.669632         1   35          1          -1              0
1437  101.151054         0    9          0           1              0
1515  101.214093         1   94          1          -1              0
343    99.113265         0   61          0           1              0
769    99.954173         1   90          1           0              1
1332   98.707711         0   25          1           0              1
1685   98.257931         1   68          0          -1              0
130   101.321681         0   19          0          -1              1
1687   98.311800         0   18          1           1              1
871    98.287575         0   55          1           1              0
1123   98.910321         1    5          0           1              0
1396  100.099332         1   13          1           1              1
87     99.532190         1   98          0          -1              1
1482  100.352478         0    6          0           0              1
330    99.698234         1   33          1           0              1
1238   99.956491         1   85          0          -1              0
466    99.513995         1   82          0          -1              1
121   100.131721         0   47          1          -1              1
1638  101.759302         0   80          1           1              0
1044   98.901070         1   65          0           1              1
1724   99.436476         1   28          1          -1              0
1095   98.888787         1   17          0          -1              0
1130   99.103715         1   19          1           0              1
1294  101.511448         0   74          1          -1              0
860   101.092942         0   83          0           0              0
1459  100.640478         0   57          1           0              0
1126  100.891232         1   76          1           0              1

[1600 rows x 6 columns]

In [12]:
test

           fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1860   98.355781         1   95          0           1              1
353   101.041435         0   66          1           0              1
1333   98.185123         1   84          1           1              1
905   100.703338         1   44          0          -1              1
1289  100.358928         1   66          0           1              0
1273   99.172544         0   15          0           1              1
938    98.609053         1   20          1           0              0
1731   98.928714         1   84          1          -1              1
65     98.703284         0   13          1           0              1
1323   99.926527         1   78          0           1              1
56     99.740171         0   24          0           1              0
1292   98.499782         0    2          0           0              0
1118  100.529446         0   75          0          -1              1
584   100.370912         0   34          0          -1              0
374   101.937650         1   47          1          -1              0
275   100.516607         1   45          1           0              1
746    98.476115         1   59          0           0              0
128   101.542392         0   52          1           0              0
1646   99.703043         1   94          0           0              1
1852  101.419831         0   59          0           0              1
674    99.140429         0   47          0           1              1
1664   99.911180         1   76          1          -1              1
1981   99.829535         0   12          1           1              1
1083  101.204633         0   29          0          -1              1
1922   99.318859         0   76          0          -1              1
99    101.981063         0   49          1          -1              1
1179  101.095940         1   34          1          -1              1
964   100.827751         1   56          0           0              1
792    98.691773         0   34          0          -1              1
29     99.959033         1   54          0           1              1
...          ...       ...  ...        ...         ...            ...
1543   98.891666         1    1          1           0              1
1803  101.300677         0    9          1           0              0
67    101.797897         0   85          0          -1              0
1737  101.074720         1   85          1          -1              1
1592  100.244305         0   23          1           1              1
1563  101.330852         1   87          0          -1              0
480    99.067359         0   46          1           1              1
1756   99.145244         1   36          1          -1              0
1912   99.427923         0   37          1           1              1
1440  100.727295         0   30          0          -1              1
1460  100.388293         1   51          1          -1              0
887    98.151567         0    2          1           1              0
422    99.494358         0    8          0           0              0
1674  100.976561         1   91          0           1              1
1449   98.102554         1   41          1           1              0
764   100.190759         1   83          0          -1              0
519   101.490375         1   76          1           0              1
1431   99.638509         1   24          1           1              1
613   100.709812         1   50          0           1              1
1530   99.700839         0    7          0          -1              0
1782  100.461831         1   56          1           1              1
1658   98.131104         0   20          0           0              1
453    99.790682         1   12          0           1              0
730    98.329731         0   28          1           0              1
534   100.755721         1    8          1          -1              1
965    98.400262         1   81          1           1              0
1284   99.436198         1   34          0           0              0
1739  101.866479         1   18          0           0              1
261   101.623971         0   12          0           1              0
535   101.751154         1   17          0           1              0

[400 rows x 6 columns]

In [13]:
X_train = train[['fever','bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()
X_test = test[['fever','bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()

In [14]:
Y_train = train[['infectionProb']].to_numpy().reshape(1600 ,)
Y_test = test[['infectionProb']].to_numpy().reshape(400 ,)

In [15]:
Y_train

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [18]:
inputFeatures = [100, 1, 22, -1, 1]
infProb = clf.predict_proba([inputFeatures])[0][1]

In [19]:
infProb

0.4858152440270045

In [20]:
pwd

'C:\\Users\\ASUS'